import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by Next.js",
};

export default function RootLayout({children}: {children: React.ReactNode;})
    {
    return  (
        <html lang="en">
            <body>
                <header
                style = {{
                        backgroundColor: "lightblue",
                        padding: "10px",
                        textAlign: "center",
                    }}>
                <p>Header Content</p>
                </header>
                {children}
                <footer
                style = {{
                    backgroundColor: "lightgray",
                    padding: "10px",
                    textAlign: "center",
                }}>
                <p>Footer Content</p>
                </footer>
            </body>                                                                 
        </html>
    );
    }